### PR TITLE
IFTTT integration

### PR DESCRIPTION
**Pull request by kenman345**
I made some local changes that I tried to remove with a rebase but ended up committing a revert instead to get it to undo those changes.

The premise is simple, I wanted to add the IFTTT functionality seen from a python script another user of the community had created. I thought that by integrating the IFTTT call to the miner we could allow the ability to be more accurate as well as reduce the calls to Nicehashs APIs to test if some miner is down.

So, I have included a screenshot of the settings in IFTTT that I have been using with my changes. I hope you find them worthy of inclusion into the software.

Also, I wanted to note a small bug I could not seem to resolve. If you open the settings window, you will see the checkbox and textbox for the IFTTT integration I created. It defaults to disabled for the textbox, but if you check the checkbox and fill in a value to the text field, you can save and the data is stored. When you re-open the settings window however, it has all that data but the text field initialized as disabled. The value is still there we just need to toggle the checkbox unchecked and then checked for the text field to re-enable and the value changed.

### CODE REVIEW

**Comment by DillonN** [comment]
Hello @kenman345, this is a neat idea. There are some formatting and other small changes I'd like to make, if you wouldn't mind. I can also fix that bug you mentioned.

**Comment by kenman345** [comment]
@DillonN Absolutely. I would love your input. Do you need access to my fork or anything to get this done? Maybe we do a pull request to a branch on the main repo so you can work on it? Just let me know what you need. Happy to see that my code can be of use.

**Comment by kenman345** [comment]
I also realized I did not include any translation for my changes. Not sure how necessary they are but that could be something we need to add before it can go into a release

**Comment by DillonN** [comment]
You do not need to give me access, you did when you made the PR

I have merged to the new master head, and changed some of the formatting back so it's easier to see the diffs. Also fixed the textbox being enabled, you had the callbacks set twice so the checkbox one wasn't updating the enabled properly

There will need to be translations before release

**Comment by kenman345** [comment]
I do not know the other languages. Is someone on the team able to help with that? 

Should we add anything to the instructions on how to use this?

**Comment by DillonN** [comment]
@kenman345 I have added translations and again merged to newest master. Also I made some changes so that you don't get a "Mining once again profitable message" when hitting start/stop buttons

Aside from that everything looks good!

(EDIT last commit to fix scaling issues from using VS on high DPI monitor)

**Comment by kenman345** [comment]
is their anything else that would need to be done for this to be included in the next release?

**Comment by DillonN** [comment]
No it looks good, thanks for the work! I will look into getting this implemented for the next version

**Comment by DillonN** [comment]
PR is merged, thanks for the contribution!

**Comment by kenman345** [comment]
Just let me know if you need anything else. I'll keep my eye out for any issues I can help out with.

**Comment by rickrs** [comment]
in text say : follow the instructions to use this new feature, but where is
the instructions? where i find tutorial for ifttt integration?

the applet in ifttt called nicehash not working in my iphone.

thanks

**Comment by kenman345** [comment]
Setup a webhook in IFTTT using these settings: https://imgur.com/qlqok4Z
It sends a notification to IFTTT when the tool identifies its no longer profitable and puts up the warning message and stops mining. It also notifies when it is back to profitability, so you know wen it starts back up.
Put the API key that IFTTT gives you into the settings of the mining software.

**Comment by tone53** [comment]
@kenman345 Can you explain more About IFTTT ? how to triger work? Thank You

**Pull request merged**
