### PR TITLE
basic WebManager

### PR DESCRIPTION
**Pull request by gacopl**
This adds a basic http server, serving nice stats of nicehash it can be hooked up to my other project nicehash-farmmanager and give you overview over all your nicehash mining rigs.

Its not ideal (stats.json file) but it gets the job done, long-term goal is to implement proper API

Quite few people are using my old 1.7.5.13 branch just because of this one feature so it may be worth adding it to official legacy

cheers

### CODE REVIEW

**Comment by gacopl** [comment]
i have rebased to your latest master

**Comment by DillonN** [comment]
Hello @gacopl, thanks for proposing the web manager. However we are currently in the process of implementing a socket connection so users can monitor their devices from https://new.nicehash.com/miner/ so for now we won't be implementing a webserver into NHML

**Comment by gacopl** [comment]
Will this be available to poll from 3rdparty sources, or it will only
callback home to nicehashminer ?

2017-08-03 11:00 GMT+02:00 Dillon Newell <notifications@github.com>:

**Comment by DillonN** [comment]
At the moment it is only going to connect to the NiceHash website

**Pull request closed without merging**
