### PR TITLE
DSTM support

### PR DESCRIPTION
**Pull request by LufyCZ**
Benchmarking doesn't work, and you have to manually download the miner, and place zm.exe and pthreadVC2.dll into the /bin_3rdparty/zminer/ folder.

### CODE REVIEW

**Comment by Krassikn** [comment]
Is there Windows version ?

**Comment by LufyCZ** [comment]
That is the Windows version, you just need to compile it in Visual Studio

**Comment by Krassikn** [comment]
Cant do that.

**Comment by LufyCZ** [comment]
https://github.com/LufyCZ/NiceHashMinerLegacy/releases/tag/1.8.1.6

**Comment by Krassikn** [comment]
Thanks.

**Comment by Krassikn** [comment]
Man, this is not 1.8.1.6. You compiled 1.8.2pre version. Can you do the 1.8.1.6

**Comment by LufyCZ** [comment]
Whoops, sorry, gimme a sec

Edit: It's up

**Comment by Krassikn** [comment]
Great. 10X!

**Comment by Krassikn** [comment]
Its not working. Nicehash miner doesnt start the zminer.

**Comment by LufyCZ** [comment]
You have to manually download it, it works, I'm running the build rn

**Comment by Krassikn** [comment]
I did this. Nicehash miner just ignore the zminer and never use it. It was previously working on the 1.8.2pre you uploaded before.

**Comment by LufyCZ** [comment]
It looks like EWBF doesn't work either (for me) on 1.8.1.6, resulting in the same error message as ZMiner. I will look into it tomorrow.

Btw don't merge yet, this seems to be an issue I'll try to fix

**Comment by davey1343** [comment]
Any update on this?

**Comment by LufyCZ** [comment]
No, sorry, I was not able to fix it as I have no idea what could be wrong. You can use the 1.8.2.0-pre2 tho

**Comment by davey1343** [comment]
Ok. Could you link me to a compiled version if possible? Thanks

**Comment by LufyCZ** [comment]
Here
(https://github.com/LufyCZ/NiceHashMinerLegacy/releases/download/1.8.2.0-Pre2/Release.zip)
 you go.

**Comment by davey1343** [comment]
Thanks! Couldn't find the 1.8.2 - Kept compiling the older version haha

**Pull request closed without merging**
