### PR TITLE
Restart when CUDA device is lost

### PR DESCRIPTION
**Pull request by sebeksd**
New option in settings to periodically query CUDA GPUs. When at least one GPU is lost the application will run OnGPUsLost.bat.
I used bat script instead of directly restarting machine because some people (me to) may want to do some custom stuff, not only simple restart.

GPU is lost because instability in algo switching (for some algos more than other) and also if GPU is not 100% stable (OC, UV etc.).
This option work only for Nvidia GPUs.
It is a workaround (but not only) for #74 and similar

### CODE REVIEW

**Comment by NameUnavailable** [comment]
This would be a really nice feature to add to nicehash miner

**Comment by Woldemar83M** [comment]
Really looking forward to when it will be possible at nicehash miner the decision problem with loss of video device when changing algorithms on the cards! 

At the moment it saves only restart the entire system. When I noticed that the profit fell.

I understand the solution will appear in the next version of the program?

**Comment by sebeksd** [comment]
As @Sav87 mentioned in #284 we can restart drivers instead of entire machine, I test it and it seems to work very nice so I added it to default script, inside a script is guide how to enable/use it.

Main advantage is this work faster then restart of entire machine

**Comment by DillonN** [comment]
@sebeksd, this looks good, thanks for the contribution. There are a few modifications I'd like to make (formatting) if you don't mind. Also, is there a reason why you added an overload to `QueryVideoControllers()` (line 316 of `ComputeDeviceManager.cs`)? It does not look like it is referenced anywhere else.

I will also fix the merge conflict recently created

**Comment by sebeksd** [comment]
@DillonN You can modify everything you think need to be modify, it's not a problem for me :) About  QueryVideoControllers this was first attempt to check if GPU was lost, but Windows see all cards all the time. You can look at method CheckVideoControllersCountMismath(), I leave there a comment, if you like I can reverse this changes (they are unnecessary right now).

**Pull request merged**
