### PR TITLE
Update ru.lang

### PR DESCRIPTION
**Pull request by adem4ik**

### CODE REVIEW

**Comment by DillonN** [comment]
Thanks for your contribution. Would you mind going over the new translations from commit bcf3f968203f2dbe3f89c4390f24cb3eafcdd9cb?

**Comment by adem4ik** [comment]
Hm, I've tried it by manually adding new translation strings, but seems like it has produced conflicts.

Is it fine for you? Otherwise I can re-create pull request.

**Comment by DillonN** [comment]
No worries, I'll resolve the conflicts and merge. Thanks again!

**Comment by adem4ik** [comment]
Great, thanks!

**Pull request merged**
