### PR TITLE
No need to accept the pull request. Just need some comments on the things I'm doing.

### PR DESCRIPTION
**Pull request by ahelguerrero**
Hi,

Made some code refactoring. Implemented some checks.

I wanted to ask why are we NVAPI for power usage? I changed it to one of the NVML functions: 
NvmlNativeMethods.nvmlDeviceGetPowerManagementLimitConstraints(), and   NvmlNativeMethods.nvmlDeviceGetPowerManagementDefaultLimit().
Is NVAPI better? 

I also included where one of the user program gets stuck because it fails to initialize.

I don't not have enough resources to test my code on other machines, so I do not know what effects will cause to other machines.

Can you (@S74nk0 or @luc1an24 ) provide some insight? Much appreciated!

Thank you for your time in reading this.

EDIT:
The reason for the checks is that some devices might not support the power mode or any other mode (It could be the  NVML API needs to be fixed, most likely). DeviceMonitor gets stuck in an infinite loop whenever power supply is not found, so it tries again and again.

### CODE REVIEW

**Comment by ahelguerrero** [comment]
I crei.

**Comment by S74nk0** [comment]
Hi @ahelguerrero. Sorry for long wait. I will be brief. We use NVAPI because of legacy reasons as NVAPI provided APIs that NVML did not at the time of writing. We are planing to remove NVAPI with NVML where possible. With newer NVML versions there is API support for power querying and setting. 

NHM has a serious bug if one of the NVIDIA monitoring functions always fail and this causes a inf re-try loop. We are working on a fix for this.

Again sorry for not responding earlier.

**Comment by ahelguerrero** [comment]
Thank you for the insight. Much appreciated. In the mean time, I will try to help out with test cases and test it more on my laptop and desktop. By the way, I cannot replicate Wetik2 bug. It seems that his problem is not being able to initialize the Nvml API. Do not know why. It seems that he can mine with his gpu.

**Comment by S74nk0** [comment]
Wetik2 bug should be resolved with https://github.com/nicehash/NiceHashMiner/pull/1750. The issue is with restarting the NVML API. When the driver crashes a restart is needed in order for the handles to work. The bug was actually a infinite loop restart cycle. The new implementation will check only per GPU issues and will execute NVML restart without blocking the whole program on certain nvm errors. If the NVML restart doesn't fix the monitoring API after a certain N-tries it will permanently stop trying to restart NVML. Now we use only NVAPI for fan RPM speed (there is no general NVML API for this).

**Pull request closed without merging**
