### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by riccardoruspoli**
I've made this italian translation for NHML

### CODE REVIEW

**Comment by adem4ik** [comment]
Hi, just to let you know that the stats button on the bottom panel is going to be hidden with some conditions. I've met the same behaviour in Russian and fixed it by using short form of the "Day" translation. If you think that it is very critical I suggest you to think about shorter word forms on the bottom panel.

**Comment by DillonN** [comment]
Thanks @Rikifire, could you please add translations for the IFTTT feature introduced in `1.8.1.2`? These are `Form_Settings_ToolTip_UseIFTTT`, `Form_Settings_General_UseIFTTT`, and `Form_Settings_IFTTTAPIKey`

**Comment by riccardoruspoli** [comment]
Done

**Comment by DillonN** [comment]
Thanks for the contribution!

**Pull request merged**
