### PR TITLE
Optional connection warning message box

### PR DESCRIPTION
**Pull request by fakelogo**
#15 I am no .NET developer. But please use it if it does the trick. This will save us a lot of trouble.

### CODE REVIEW

**Comment by DillonN** [comment]
Thanks for the contribution. Currently the checkbox must be added to the settings form through the designer for this to work. I can do this in a bit if you don't want to

In the meantime, if anyone is kind enough to provide some translations, they could be implemented (@adem4ik and @drkskwlkr may be willing to help out)

**Comment by fakelogo** [comment]
@DillonN I would love to, but I guess I do not have the proper IDE. I edited the files just with vim :) I'll be grateful for help with the designer. Sorry for the half-way work. 

Thanks.

**Comment by adem4ik** [comment]
@DillonN I'll provide ru.lang translation if that pull request will be merged.

**Comment by DillonN** [comment]
@fakelogo not a problem, I can put it in

@adem4ik thank you!

**Comment by DillonN** [comment]
I've added the checkbox and will merge now. Thanks for the contribution!

**Comment by fefsf** [comment]
So what will happen now if NHML starts and no internet connection has been established yet? Hopefully it will just retry every 15 seconds or so? That would be great

**Pull request merged**
